//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18034
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeCallManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20:00:00")]
        public global::System.TimeSpan CallStopTime {
            get {
                return ((global::System.TimeSpan)(this["CallStopTime"]));
            }
            set {
                this["CallStopTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("あと1分ぐらいで通話を終了します")]
        public string OneMinuteMessage {
            get {
                return ((string)(this["OneMinuteMessage"]));
            }
            set {
                this["OneMinuteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("あと3分ぐらいで通話を終了します")]
        public string ThreeMinuteMessage {
            get {
                return ((string)(this["ThreeMinuteMessage"]));
            }
            set {
                this["ThreeMinuteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("あと5分ぐらいで通話を終了します")]
        public string FiveMinuteMessage {
            get {
                return ((string)(this["FiveMinuteMessage"]));
            }
            set {
                this["FiveMinuteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("あと10分ぐらいで通話を終了します")]
        public string TenMinuteMessage {
            get {
                return ((string)(this["TenMinuteMessage"]));
            }
            set {
                this["TenMinuteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("あと15分ぐらいで通話を終了します")]
        public string FifteenMinuteMessage {
            get {
                return ((string)(this["FifteenMinuteMessage"]));
            }
            set {
                this["FifteenMinuteMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSignAfter {
            get {
                return ((bool)(this["IsSignAfter"]));
            }
            set {
                this["IsSignAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[通話マネージャーから送信]")]
        public string Sign {
            get {
                return ((string)(this["Sign"]));
            }
            set {
                this["Sign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsBootVisible {
            get {
                return ((bool)(this["IsBootVisible"]));
            }
            set {
                this["IsBootVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsTrayNotificationEnable {
            get {
                return ((bool)(this["IsTrayNotificationEnable"]));
            }
            set {
                this["IsTrayNotificationEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("通話を終了しました")]
        public string DisconnectMessage {
            get {
                return ((string)(this["DisconnectMessage"]));
            }
            set {
                this["DisconnectMessage"] = value;
            }
        }
    }
}
